-- Mirrors lib/seed-facts.ts.
insert into public.facts (entity_type, entity_slug, field, value, source_url, verified_at, verification_method, watch_priority) values
  ('regulation', 'cmmc', 'phase_ii_status', 'Phase II suspended July 13, 2026. New procurements currently cannot designate a Level 2 or Level 3 assessment requirement, and waiver procedures are halted pending a 60-day CIO review. Level 1 self-assessment and DFARS 252.204-7012/7019/7020 remain in force.', 'https://dodcio.defense.gov/Portals/0/Documents/Library/ImplementingSuspensionCMMC-PhaseII.pdf', '2026-08-30', 'official_page', 'high'),
  ('regulation', '8a', 'social_disadvantage_rule', '⟦VERIFY: high-priority Regulatory Watch. Proposed rule June 11, 2026; final rule August 11, 2026; effective September 10, 2026. Confirm the rule took effect as scheduled and check for litigation before publishing anything in the past tense.⟧', 'https://www.sba.gov/article/2026/06/11/sba-reforms-8a-business-development-program-end-racial-discrimination-federal-contracting', '2026-08-30', 'official_page', 'high'),
  ('program', 'set-asides', 'self_certification', 'None of the major socioeconomic set-asides are self-certified. Applications run through certifications.sba.gov, not certify.sba.gov.', 'https://certifications.sba.gov', '2026-08-30', 'official_page', 'high'),
  ('regulation', 'nist-800-171', 'revision', '⟦VERIFY: NIST SP 800-171 Rev 3 transition timing. CMMC L2 still maps to Rev 2 in the cited DoD CIO material.⟧', 'https://dodcio.defense.gov/CMMC/', '2026-08-30', 'official_page', 'high'),
  ('resource', 'dod-portals', 'portal_urls', 'DoD is officially the Department of War. Sites and portal URLs are mid-transition across dodcio.defense.gov, war.gov, and business.defense.gov.', 'https://www.whitehouse.gov/presidential-actions/2025/09/restoring-the-united-states-department-of-war/', '2026-08-30', 'official_page', 'high'),
  ('program', 'sam-gov', 'registration_cost', 'Registration in SAM.gov is always free. The government will never ask you to pay to register, update, or renew.', 'https://sam.gov/entity-registration', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'apex-alabama', 'name', 'APEX Accelerator of Alabama', 'https://apexal.org', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'apex-alabama', 'address', 'Business Administration Building, 800 Ben Graves Drive NW, Suite 126, Huntsville, AL 35816', 'https://apexal.org', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'apex-alabama', 'email', 'sbdc@uah.edu', 'https://www.uah.edu/sbdc/apex', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'apex-alabama', 'phone', '⟦VERIFY: 256-824-7232 (SBDC) / 256-824-2739 (APEX)⟧', 'https://apexal.org', '2026-08-30', 'secondary', 'normal'),
  ('resource', 'apex-alabama', 'advising_cost', 'Advising is provided at no cost.', 'https://apexal.org', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'apex-alabama', 'website', 'https://apexal.org', 'https://apexal.org', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'apex-alabama', 'booking', 'Use the contact path on apexal.org. Confirm the current appointment or intake step on that page before you call.', 'https://apexal.org', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sba-alabama', 'name', 'SBA Alabama District Office', 'https://www.sba.gov', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sba-alabama', 'address', '2 North Twentieth Street, Suite 325, Birmingham, AL 35203', 'https://www.sba.gov', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sba-alabama', 'phone', '(205) 290-7101', 'https://www.sba.gov', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sba-alabama', 'huntsville_satellite', 'No Huntsville satellite. Local delivery runs through SBDC/APEX and SCORE.', 'https://www.sba.gov', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sba-alabama', 'website', 'https://www.sba.gov', 'https://www.sba.gov', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sba-alabama', 'booking', 'The district office is in Birmingham. Confirm hours and intake on sba.gov before you call. There is no Huntsville satellite.', 'https://www.sba.gov', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'acc-rsa', 'name', 'Army Contracting Command–Redstone Arsenal (ACC-RSA)', 'https://www.army.mil/acc-rsa', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'acc-rsa', 'what_it_buys', 'Largest contracting center in the Army. 900+ acquisition professionals; 29 ACAT I programs. Weapon systems, SETA, prototyping, FMS, installation and range support.', 'https://www.army.mil/acc-rsa', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'acc-rsa', 'fy2024_contracts', '14,380+ contracts worth $28B+ in FY2024.', 'https://www.army.mil/acc-rsa', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'acc-rsa', 'sb_contact', 'ACC-RSA publishes no individual small-business contact on its own site, only a general Small Business Office portal with appointment booking.', 'https://www.army.mil/acc-rsa', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'amcom', 'name', 'AMCOM', 'https://www.amcom.army.mil', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'amcom', 'what_it_buys', 'Aircraft manufacturing, guided missile and space vehicle manufacturing, engineering services, aviation transportation support, R&D.', 'https://www.amcom.army.mil', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'smdc', 'name', 'SMDC', 'https://www.smdc.army.mil', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'smdc', 'what_it_buys', 'R&D in physical/engineering/life sciences, engineering services, facilities support, security and patrol services, computer facilities management.', 'https://www.smdc.army.mil', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'mda', 'name', 'MDA', 'https://www.mda.mil/business/opportunities.html', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'mda', 'what_it_buys', 'Missile Defense System requirements and components.', 'https://www.mda.mil/business/opportunities.html', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'nasa-msfc', 'name', 'NASA MSFC', 'https://doingbusiness.msfc.nasa.gov', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'nasa-msfc', 'what_it_buys', 'Space vehicle manufacturing, propulsion, R&D, engineering and facilities support.', 'https://doingbusiness.msfc.nasa.gov', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'amc', 'name', 'Army Materiel Command', 'https://www.amc.army.mil', '2026-08-30', 'official_page', 'normal'),
  ('agency', 'amc', 'what_it_buys', 'HQ at Redstone. Global Army supply chain, logistics, sustainment.', 'https://www.amc.army.mil', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'boeing', 'name', 'Boeing', 'https://www.boeingsuppliers.com/supplier_diversity.html', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'lockheed', 'name', 'Lockheed Martin', 'https://www.lockheedmartin.com/en-us/suppliers/small-business-programs.html', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'northrop', 'name', 'Northrop Grumman', 'https://www.northropgrumman.com/suppliers/osbp', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'leidos-dynetics', 'name', 'Leidos / Dynetics', 'https://www.leidos.com/suppliers/small-business-relationships', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'rtx', 'name', 'RTX', 'https://www.rtx.com/suppliers/small-business', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'l3harris-aerojet', 'name', 'L3Harris / Aerojet Rocketdyne', 'https://arsuppliernet.l3harris.com/suppliernet/doing-business-ar/small-business-and-small-business-liaison-officers-sblo', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'sierra-space', 'name', 'Sierra Space', 'https://www.sierraspace.com/suppliers/', '2026-08-30', 'official_page', 'normal'),
  ('event', 'apbi', 'name', 'AMCOM / Team Redstone APBI', 'https://www.amcom.army.mil/News/News-Releases/Article/3275579/team-redstones-advance-planning-briefings-to-industry-slated-for-march-21-23/', '2026-08-30', 'official_page', 'normal'),
  ('event', 'apbi', 'dates', 'Historically March. ⟦VERIFY: current dates via AMCOM news releases⟧', 'https://www.amcom.army.mil/News/News-Releases/', '2026-08-30', 'secondary', 'normal'),
  ('event', 'ndia-tennessee-valley', 'name', 'NDIA Tennessee Valley Chapter', 'https://www.ndiatennvalley.org/', '2026-08-30', 'official_page', 'normal'),
  ('event', 'ndia-tennessee-valley', 'referral_code', 'NDITVC', 'https://www.ndiatennvalley.org/', '2026-08-30', 'official_page', 'normal'),
  ('event', 'ndia-tennessee-valley', 'dates', 'Year-round. ⟦VERIFY: current chapter dates⟧', 'https://www.ndiatennvalley.org/', '2026-08-30', 'secondary', 'normal'),
  ('event', 'smd-symposium', 'name', 'Space and Missile Defense Symposium', 'https://smdsymposium.org', '2026-08-30', 'official_page', 'normal'),
  ('event', 'smd-symposium', 'dates', '⟦VERIFY: next occurrence dates; brief cites Aug 10–12, 2027⟧', 'https://smdsymposium.org', '2026-08-30', 'secondary', 'normal'),
  ('event', 'hsv-chamber', 'name', 'Huntsville/Madison County Chamber — Team Redstone', 'https://hsvchamber.org/team-redstone', '2026-08-30', 'official_page', 'normal'),
  ('event', 'hsv-chamber', 'cost', '⟦VERIFY: Chamber programs are often membership- or fee-based. Do not describe them as free without checking.⟧', 'https://hsvchamber.org/team-redstone', '2026-08-30', 'secondary', 'normal'),
  ('resource', 'uah-sbdc', 'name', 'UAH Small Business Development Center', 'https://www.uah.edu/sbdc', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'uah-sbdc', 'website', 'https://www.uah.edu/sbdc', 'https://www.uah.edu/sbdc', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'uah-sbdc', 'booking', '⟦VERIFY: UAH SBDC booking path⟧', 'https://www.uah.edu/sbdc', '2026-08-30', 'secondary', 'normal'),
  ('resource', 'score', 'name', 'SCORE', 'https://www.score.org', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'score', 'website', 'https://www.score.org', 'https://www.score.org', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'score', 'advising_cost', 'SCORE mentoring is offered at no cost on the national site.', 'https://www.score.org', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'score', 'booking', '⟦VERIFY: SCORE Huntsville booking path⟧', 'https://www.score.org', '2026-08-30', 'secondary', 'normal'),
  ('resource', 'sba-7j', 'name', 'SBA 7(j) Management and Technical Assistance Program', 'https://www.sba.gov/federal-contracting/contracting-assistance-programs/7j-management-technical-assistance-program', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sba-7j', 'website', 'https://www.sba.gov/federal-contracting/contracting-assistance-programs/7j-management-technical-assistance-program', 'https://www.sba.gov/federal-contracting/contracting-assistance-programs/7j-management-technical-assistance-program', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sba-7j', 'booking', '⟦VERIFY: SBA 7(j) / Empower to Grow current enrollment URL⟧', 'https://www.sba.gov/federal-contracting/contracting-assistance-programs/7j-management-technical-assistance-program', '2026-08-30', 'secondary', 'normal'),
  ('resource', 'dau', 'name', 'Defense Acquisition University', 'https://www.dau.edu/', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'dau', 'website', 'https://www.dau.edu/', 'https://www.dau.edu/', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'dau', 'booking', '⟦VERIFY: DAU public course list relevant to new vendors⟧', 'https://www.dau.edu/', '2026-08-30', 'secondary', 'normal'),
  ('program', 'uei', 'what_it_is', 'Unique Entity ID. Replaced DUNS in April 2022. Free. Issued through SAM.gov entity registration.', 'https://sam.gov/entity-registration', '2026-08-30', 'official_page', 'normal'),
  ('program', 'cage', 'what_it_is', 'Commercial and Government Entity code. Free. Issued concurrently with SAM registration.', 'https://www.acquisition.gov/far/52.204-16', '2026-08-30', 'official_page', 'normal'),
  ('program', 'sam-gov', 'processing_time', 'SAM.gov registration is free. Processing can take up to 10 business days.', 'https://sam.gov/entity-registration', '2026-08-30', 'official_page', 'normal'),
  ('program', 'sam-gov', 'checklist', 'https://sam.gov/sites/default/files/2024-11/entity-checklist.pdf', 'https://sam.gov/entity-registration', '2026-08-30', 'official_page', 'normal'),
  ('program', 'sam-gov', 'renewal', 'Annual renewal is free. Required every 365 days or the entity is ineligible for award.', 'https://sam.gov/entity-registration', '2026-08-30', 'official_page', 'normal'),
  ('program', 'sam-gov', 'gsa_warning', 'Registration is always free. The government will never ask you to pay to register, update, or renew.', 'https://content.govdelivery.com/accounts/USGSA/bulletins/358af1f', '2026-08-30', 'official_page', 'high'),
  ('program', 'sam-gov', 'phishing_alert', 'https://sam.gov/alerts/recognize-and-avoid-phishing-emails', 'https://sam.gov/alerts/recognize-and-avoid-phishing-emails', '2026-08-30', 'official_page', 'normal'),
  ('program', 'naics', 'what_it_is', 'North American Industry Classification System codes used to classify the work you do.', 'https://www.census.gov/naics/', '2026-08-30', 'official_page', 'normal'),
  ('program', 'size-standard', 'what_it_is', 'SBA size standards determine small-business status for a NAICS code.', 'https://legacy.sba.gov/document/support-table-size-standards', '2026-08-30', 'official_page', 'normal'),
  ('program', 'size-standard', 'official_url', 'https://www.law.cornell.edu/cfr/text/13/121.101', 'https://www.law.cornell.edu/cfr/text/13/121.101', '2026-08-30', 'official_page', 'normal'),
  ('regulation', 'far-19-7', 'subcontracting_plan', 'A prime that is not itself a small business and that is above the FAR 19.7 subcontracting-plan threshold must have a plan. A capability statement helps that prime meet the plan. It is not a favor. ⟦VERIFY: current FAR 19.702 dollar thresholds⟧', 'https://www.acquisition.gov/far/subpart-19.7', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'boeing', 'sb_portal', 'https://www.boeingsuppliers.com/supplier_diversity.html', 'https://www.boeingsuppliers.com/supplier_diversity.html', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'lockheed', 'sb_portal', 'https://www.lockheedmartin.com/en-us/suppliers/small-business-programs.html', 'https://www.lockheedmartin.com/en-us/suppliers/small-business-programs.html', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'northrop', 'sb_portal', 'https://www.northropgrumman.com/suppliers/osbp', 'https://www.northropgrumman.com/suppliers/osbp', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'leidos-dynetics', 'sb_portal', 'https://www.leidos.com/suppliers/small-business-relationships', 'https://www.leidos.com/suppliers/small-business-relationships', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'rtx', 'sb_portal', 'https://www.rtx.com/suppliers/small-business', 'https://www.rtx.com/suppliers/small-business', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'l3harris-aerojet', 'sb_portal', 'https://arsuppliernet.l3harris.com/suppliernet/doing-business-ar/small-business-and-small-business-liaison-officers-sblo', 'https://arsuppliernet.l3harris.com/suppliernet/doing-business-ar/small-business-and-small-business-liaison-officers-sblo', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'sierra-space', 'sb_portal', 'https://www.sierraspace.com/suppliers/', 'https://www.sierraspace.com/suppliers/', '2026-08-30', 'official_page', 'normal'),
  ('prime', 'blue-origin', 'name', 'Blue Origin', '⟦VERIFY: official Blue Origin site URL⟧', '2026-08-30', 'secondary', 'normal'),
  ('prime', 'blue-origin', 'no_public_portal', 'No public small-business supplier portal was found. Confirm on the company site before you send anything.', '⟦VERIFY: official Blue Origin site URL used for the portal search⟧', '2026-08-30', 'secondary', 'normal'),
  ('prime', 'torch', 'name', 'Torch Technologies', '⟦VERIFY: official Torch Technologies site URL⟧', '2026-08-30', 'secondary', 'normal'),
  ('prime', 'torch', 'no_public_portal', 'No public small-business supplier portal was found. Confirm on the company site before you send anything.', '⟦VERIFY: official Torch Technologies site URL used for the portal search⟧', '2026-08-30', 'secondary', 'normal'),
  ('prime', 'colsa', 'name', 'COLSA', '⟦VERIFY: official COLSA site URL⟧', '2026-08-30', 'secondary', 'normal'),
  ('prime', 'colsa', 'no_public_portal', 'No public small-business supplier portal was found. Confirm on the company site before you send anything.', '⟦VERIFY: official COLSA site URL used for the portal search⟧', '2026-08-30', 'secondary', 'normal'),
  ('prime', 'quantum', 'name', 'Quantum Research International', '⟦VERIFY: official Quantum Research International site URL⟧', '2026-08-30', 'secondary', 'normal'),
  ('prime', 'quantum', 'no_public_portal', 'No public small-business supplier portal was found. Confirm on the company site before you send anything.', '⟦VERIFY: official Quantum Research International site URL used for the portal search⟧', '2026-08-30', 'secondary', 'normal'),
  ('prime', 'davidson', 'name', 'Davidson Technologies', '⟦VERIFY: official Davidson Technologies site URL⟧', '2026-08-30', 'secondary', 'normal'),
  ('prime', 'davidson', 'no_public_portal', 'No public small-business supplier portal was found. Confirm on the company site before you send anything.', '⟦VERIFY: official Davidson Technologies site URL used for the portal search⟧', '2026-08-30', 'secondary', 'normal'),
  ('program', 'hubzone', 'map_url', 'https://maps.certify.sba.gov/hubzone/map', 'https://maps.certify.sba.gov/hubzone/map', '2026-08-30', 'official_page', 'high'),
  ('program', 'hubzone', 'what_it_is', 'HUBZone status is determined on SBA''s live map. This map does not publish a static Huntsville tract list.', 'https://maps.certify.sba.gov/hubzone/map', '2026-08-30', 'official_page', 'high'),
  ('program', 'wosb', 'official_url', 'https://www.sba.gov/wosb', 'https://www.sba.gov/wosb', '2026-08-30', 'official_page', 'normal'),
  ('program', 'wosb', 'what_it_is', 'Women-Owned Small Business and EDWOSB certification runs through SBA. It is not self-certified.', 'https://www.sba.gov/wosb', '2026-08-30', 'official_page', 'normal'),
  ('program', 'sdvosb', 'what_it_is', 'Service-Disabled Veteran-Owned Small Business certification moved to SBA on January 1, 2023. It is not self-certified.', 'https://certifications.sba.gov', '2026-08-30', 'official_page', 'normal'),
  ('regulation', '8a', 'sequence', 'Proposed 2026-06-11. Final 2026-08-11. Effective 2026-09-10. ⟦VERIFY: litigation and whether the effective date held⟧', 'https://www.sba.gov/article/2026/06/11/sba-reforms-8a-business-development-program-end-racial-discrimination-federal-contracting', '2026-08-30', 'official_page', 'high'),
  ('regulation', 'dfars-7012', 'in_force', 'DFARS 252.204-7012 (safeguarding covered defense information and cyber incident reporting) remains in force while CMMC Phase II is suspended.', 'https://www.acquisition.gov/dfars/252.204-7012-safeguarding-covered-defense-information-and-cyber-incident-reporting.', '2026-08-30', 'official_page', 'high'),
  ('regulation', 'dfars-7019', 'in_force', 'DFARS 252.204-7019 (notice of NIST SP 800-171 DoD assessment requirements) remains in force.', 'https://www.acquisition.gov/dfars/252.204-7019-notice-nist-sp-800-171-dod-assessment-requirements.', '2026-08-30', 'official_page', 'high'),
  ('regulation', 'dfars-7020', 'in_force', 'DFARS 252.204-7020 (NIST SP 800-171 DoD assessment requirements) remains in force.', 'https://www.acquisition.gov/dfars/252.204-7020-nist-sp-800-171-dod-assessment-requirements.', '2026-08-30', 'official_page', 'high'),
  ('resource', 'sprs', 'what_it_is', 'Supplier Performance Risk System is where DoD NIST SP 800-171 assessment scores are posted under DFARS 7019/7020.', 'https://www.sprs.csd.disa.mil/', '2026-08-30', 'official_page', 'high'),
  ('resource', 'sprs', 'official_url', 'https://www.sprs.csd.disa.mil/', 'https://www.sprs.csd.disa.mil/', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'dibnet', 'official_url', 'https://dibnet.dod.mil', 'https://dibnet.dod.mil', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'dibnet', 'what_it_is', 'DIBNet is the DoD cyber incident reporting portal used with DFARS 252.204-7012.', 'https://dibnet.dod.mil', '2026-08-30', 'official_page', 'normal'),
  ('regulation', 'dcaa', 'ffp_exception', 'DCAA-approved accounting is not required for most firm-fixed-price small-business awards. Exception: FFP over $10 million.', 'https://www.dcaa.mil/Small-Business/Small-Business-FAQs/', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sam-opportunities', 'official_url', 'https://sam.gov', 'https://sam.gov', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sam-opportunities', 'what_it_is', 'SAM.gov is the official place to read federal opportunities, including sources sought notices and solicitations.', 'https://sam.gov', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'sources-sought', 'rule', 'Sources sought notices come before solicitations. Read FAR Part 5 before you treat a solicitation as the first signal.', 'https://www.acquisition.gov/far/part-5', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'rule-of-two', 'rule', 'FAR 19.502-2 (the Rule of Two) tells a contracting officer to set an acquisition aside for small business when there is a reasonable expectation of two or more responsible small-business offers at fair market price.', 'https://www.acquisition.gov/far/19.502-2', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'subnet', 'official_url', 'https://subnet.sba.gov/client/dsp_Landing1.cfm', 'https://subnet.sba.gov/client/dsp_Landing1.cfm', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'dsbs', 'official_url', 'https://search.certifications.sba.gov/', 'https://search.certifications.sba.gov/', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'usaspending', 'official_url', 'https://www.usaspending.gov/', 'https://www.usaspending.gov/', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'usaspending', 'what_it_is', 'USAspending publishes federal award data. Use it to see who already holds work, not as a forecast of your first award.', 'https://www.usaspending.gov/analyst-guide', '2026-08-30', 'official_page', 'normal'),
  ('resource', 'gsa-schedule', 'new_business_note', 'Do not chase a GSA Schedule as a first move. Learn the Schedule path after you can point to work and a NAICS story.', 'https://www.gsa.gov/small-business/small-business-resources/training-resources/getting-on-the-gsa-schedule', '2026-08-30', 'official_page', 'normal');

insert into public.changes (headline, detail, source_url, effective_date) values
  ('CMMC Phase II suspended', 'The November 10, 2026 deadline for mandatory Level 2 third-party (C3PAO) certification is no longer in effect. Level 1 self-assessment and DFARS 252.204-7012/7019/7020 remain in force.', 'https://dodcio.defense.gov/Portals/0/Documents/Library/ImplementingSuspensionCMMC-PhaseII.pdf', '2026-07-13'),
  ('8(a) social-disadvantage presumption under rule change', '⟦VERIFY: high-priority Regulatory Watch. Confirm the rule took effect as scheduled and check for litigation before publishing anything in the past tense.⟧', 'https://www.sba.gov/article/2026/06/11/sba-reforms-8a-business-development-program-end-racial-discrimination-federal-contracting', '2026-09-10'),
  ('Department of War rebrand', 'DoD is officially the Department of War. Sites and portal URLs are mid-transition across dodcio.defense.gov, war.gov, and business.defense.gov.', 'https://www.whitehouse.gov/presidential-actions/2025/09/restoring-the-united-states-department-of-war/', '2025-09-01');
